In [124]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report
import sklearn.metrics

In [18]:
df_cats = pd.DataFrame({'pred_dog': [46, 13], 'pred_cat': [7, 34]}, index=['Dog', 'Cat'])
df_cats

     pred_dog  pred_cat
Dog        46         7
Cat        13        34

In [27]:
# In the context of this problem, what is a false negative?
df = pd.DataFrame([['True Negative', 'False positive'], ['False Negative', 'True Positive']], columns=df_cats.columns, index=df_cats.index)
df
# In the context of this problem, what is a false negative?
df + '=' + df_cats.values.astype(str)

              pred_dog          pred_cat
Dog   True Negative=46  False positive=7
Cat  False Negative=13  True Positive=34

In [36]:
# Recall: TP / (TP + FN)
# Precision: TP / (TP + FP)
# Accuracy : (TP + TN) / (TP + TN + FP + FN)
# How would you describe this model?

# Recall:
recall = 34 / (34 + 13)
# Precision:
precision = 34 / (34 + 7)
# Accuracy : 
accuracy = (34 + 46) / df_cats.values.sum()
print('Recall=',recall)
print('Precision=',precision)
print('Accuracy=',accuracy)

Recall= 0.723404255319149
Precision= 0.8292682926829268
Accuracy= 0.8

###### 3)You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.

Use the predictions dataset and pandas to help answer the following questions:

An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?
OPTIMIZE FOR: RECALL

Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case? -OPTIMIZE FOR: PRECISION

In [45]:
df = pd.read_csv('c3.csv')
df

        actual     model1     model2     model3
0    No Defect  No Defect     Defect  No Defect
1    No Defect  No Defect     Defect     Defect
2    No Defect  No Defect     Defect  No Defect
3    No Defect     Defect     Defect     Defect
4    No Defect  No Defect     Defect  No Defect
..         ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect
196     Defect     Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect
199  No Defect  No Defect  No Defect     Defect

[200 rows x 4 columns]

In [50]:
df['baseline'] = 'No Defect'
df

        actual     model1     model2     model3   baseline
0    No Defect  No Defect     Defect  No Defect  No Defect
1    No Defect  No Defect     Defect     Defect  No Defect
2    No Defect  No Defect     Defect  No Defect  No Defect
3    No Defect     Defect     Defect     Defect  No Defect
4    No Defect  No Defect     Defect  No Defect  No Defect
..         ...        ...        ...        ...        ...
195  No Defect  No Defect     Defect     Defect  No Defect
196     Defect     Defect  No Defect  No Defect  No Defect
197  No Defect  No Defect  No Defect  No Defect  No Defect
198  No Defect  No Defect     Defect     Defect  No Defect
199  No Defect  No Defect  No Defect     Defect  No Defect

[200 rows x 5 columns]

In [68]:
subset_actual = df[df.actual == 'Defect']
print('Model(1)=',(subset_actual.actual == subset_actual.model1).mean())
print('Model(2)=',(subset_actual.actual == subset_actual.model2).mean())
print('Model(3)=',(subset_actual.actual == subset_actual.model3).mean())
#model3 has a 81 percent for internal team

Model(1)= 0.5
Model(2)= 0.5625
Model(3)= 0.8125

In [71]:
#Which evaluation metric would be appropriate here? Which model would be the best fit for this use case
#markting model 1 
subset = df[df.model1 == 'Defect']
subset = df[df.model2 == 'Defect']
subset = df[df.model3 == 'Defect']
print('Model(1)=',(subset.actual == subset.model1).mean())
print('Model(2)=',(subset.actual == subset.model2).mean())
print('Model(3)=',(subset.actual == subset.model3).mean())

Model(1)= 0.9292929292929293
Model(2)= 0.6060606060606061
Model(3)= 0.13131313131313133

###### 4)You are working as a data scientist for Gives You Paws â„¢, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

Several models have already been developed with the data, and you can find their results here.

Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?
Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?
Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?

In [111]:
# Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) 
# and answer the following questions:
Paws=pd.read_csv('gives_you_paws.csv')
Paws

     actual model1 model2 model3 model4
0       cat    cat    dog    cat    dog
1       dog    dog    cat    cat    dog
2       dog    cat    cat    cat    dog
3       dog    dog    dog    cat    dog
4       cat    cat    cat    dog    dog
...     ...    ...    ...    ...    ...
4995    dog    dog    dog    dog    dog
4996    dog    dog    cat    cat    dog
4997    dog    cat    cat    dog    dog
4998    cat    cat    cat    cat    dog
4999    dog    dog    dog    dog    dog

[5000 rows x 5 columns]

In [113]:
df['baseline'] = 'dog'
df

     actual model1 model2 model3 model4 baseline
0       cat    cat    dog    cat    dog      dog
1       dog    dog    cat    cat    dog      dog
2       dog    cat    cat    cat    dog      dog
3       dog    dog    dog    cat    dog      dog
4       cat    cat    cat    dog    dog      dog
...     ...    ...    ...    ...    ...      ...
4995    dog    dog    dog    dog    dog      dog
4996    dog    dog    cat    cat    dog      dog
4997    dog    cat    cat    dog    dog      dog
4998    cat    cat    cat    cat    dog      dog
4999    dog    dog    dog    dog    dog      dog

[5000 rows x 6 columns]

In [110]:
subset = df[df.actual == 'dog']
print('Model(1)=',(subset.actual == subset.model1).mean())
print('Model(2)=',(subset.actual == subset.model2).mean())
print('Model(3)=',(subset.actual == subset.model3).mean())
print('Model(4)=',(subset.actual == subset.model4).mean())

Model(1)= 0.803318992009834
Model(2)= 0.49078057775046097
Model(3)= 0.5086047940995697
Model(4)= 0.9557467732022127

In [107]:
print('                                 Model(1)')
print(pd.DataFrame(classification_report(df.actual, df.model1,output_dict=True)))
print('                                 Model(2)')
print(pd.DataFrame(classification_report(df.actual, df.model2,output_dict=True)))
print('                                 Model(3)')
print(pd.DataFrame(classification_report(df.actual, df.model3,output_dict=True)))
print('                                 Model()')
print(pd.DataFrame(classification_report(df.actual, df.model4,output_dict=True)))

                                 Model(1)
                   cat          dog  accuracy    macro avg  weighted avg
precision     0.689772     0.890024    0.8074     0.789898      0.820096
recall        0.815006     0.803319    0.8074     0.809162      0.807400
f1-score      0.747178     0.844452    0.8074     0.795815      0.810484
support    1746.000000  3254.000000    0.8074  5000.000000   5000.000000
                                 Model(2)
                   cat          dog  accuracy    macro avg  weighted avg
precision     0.484122     0.893177    0.6304     0.688649      0.750335
recall        0.890607     0.490781    0.6304     0.690694      0.630400
f1-score      0.627269     0.633479    0.6304     0.630374      0.631310
support    1746.000000  3254.000000    0.6304  5000.000000   5000.000000
                                 Model(3)
                   cat          dog  accuracy    macro avg  weighted avg
precision     0.358347     0.659888    0.5096     0.509118      0.554590
recall        0.511455     0.508605    0.5096     0.510030      0.509600
f1-score      0.421425     0.574453    0.5096     0.497939      0.521016
support    1746.000000  3254.000000    0.5096  5000.000000   5000.000000
                                 Model()
                   cat          dog  accuracy    macro avg  weighted avg
precision     0.807229     0.731249    0.7426     0.769239      0.757781
recall        0.345361     0.955747    0.7426     0.650554      0.742600
f1-score      0.483755     0.828560    0.7426     0.656157      0.708154
support    1746.000000  3254.000000    0.7426  5000.000000   5000.000000

In [114]:
# In terms of accuracy, how do the various models compare to the baseline model? 
# Are any of the models better than the baseline?
# phase 2: Precision
subset = df[df.model1 == 'dog']
(subset.actual == subset.model1).mean()

0.8900238338440586

###### Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.
sklearn.metrics.accuracy_score

sklearn.metrics.precision_score

sklearn.metrics.recall_score

sklearn.metrics.classification_report

In [127]:
sklearn.metrics.accuracy_score(df.actual, df.model1)

0.8074

In [128]:
sklearn.metrics.precision_score(df.actual, df.model1, average=None)

array([0.68977218, 0.89002383])

In [130]:
sklearn.metrics.recall_score(df.actual, df.model1, average=None)

array([0.81500573, 0.80331899])

In [115]:
print('                                 Model(1)')
print(pd.DataFrame(classification_report(df.actual, df.model1,output_dict=True)))
print('                                 Model(2)')
print(pd.DataFrame(classification_report(df.actual, df.model2,output_dict=True)))
print('                                 Model(3)')
print(pd.DataFrame(classification_report(df.actual, df.model3,output_dict=True)))
print('                                 Model()')
print(pd.DataFrame(classification_report(df.actual, df.model4,output_dict=True)))

                                 Model(1)
                   cat          dog  accuracy    macro avg  weighted avg
precision     0.689772     0.890024    0.8074     0.789898      0.820096
recall        0.815006     0.803319    0.8074     0.809162      0.807400
f1-score      0.747178     0.844452    0.8074     0.795815      0.810484
support    1746.000000  3254.000000    0.8074  5000.000000   5000.000000
                                 Model(2)
                   cat          dog  accuracy    macro avg  weighted avg
precision     0.484122     0.893177    0.6304     0.688649      0.750335
recall        0.890607     0.490781    0.6304     0.690694      0.630400
f1-score      0.627269     0.633479    0.6304     0.630374      0.631310
support    1746.000000  3254.000000    0.6304  5000.000000   5000.000000
                                 Model(3)
                   cat          dog  accuracy    macro avg  weighted avg
precision     0.358347     0.659888    0.5096     0.509118      0.554590
recall        0.511455     0.508605    0.5096     0.510030      0.509600
f1-score      0.421425     0.574453    0.5096     0.497939      0.521016
support    1746.000000  3254.000000    0.5096  5000.000000   5000.000000
                                 Model()
                   cat          dog  accuracy    macro avg  weighted avg
precision     0.807229     0.731249    0.7426     0.769239      0.757781
recall        0.345361     0.955747    0.7426     0.650554      0.742600
f1-score      0.483755     0.828560    0.7426     0.656157      0.708154
support    1746.000000  3254.000000    0.7426  5000.000000   5000.000000